version: '3.8'

services:
  mysql_8:
    image: arm64v8/mysql
    container_name: mysql_8
    environment:
      MYSQL_ROOT_PASSWORD: nyw
    ports:
      - "3309:3306"  # Map host port 3309 to container port 3306
    volumes:
      - ./mysql_8:/etc/mysql/conf.d  # Mount a custom configuration directory

  mysql_5_6:
    platform: linux/amd64
    image: mysql:5.6
    container_name: mysql_5_6
    environment:
      MYSQL_ROOT_PASSWORD: nyw
    ports:
      - "3310:3306"  # Map host port 3310 to container port 3306
    volumes:
      - ./mysql_5_6:/etc/mysql/conf.d  # Mount a custom configuration directory
      - ./initdb:/docker-entrypoint-initdb.d  # Mount the directory containing the SQL script
