version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: classicmodels
    ports:
      - "3309:5432"  # Map host port 3309 to container port 5432
    volumes:
      - ./scripts:/tmp/scripts  # Mount the directory containing the SQL script

  mysql_5_6:
    platform: linux/amd64
    image: mysql:5.6
    container_name: mysql_5_6
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3310:3306"  # Map host port 3310 to container port 3306
    volumes:
      - ./mysql_5_6:/etc/mysql/conf.d  # Mount a custom configuration directory
      - ./initdb:/docker-entrypoint-initdb.d  # Mount the directory containing the SQL script
